version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      
  build:
    commands:
      - mkdir -p code/lib
      - aws s3 cp s3://sap-sources/SAPJCO code/lib --recursive
      - sam build
    
#post_build:
#  commands:
    #- sam package --output-template-file packaged.yml --s3-bucket sap-monitor
    #- sam publish --template packaged.yml --region eu-central-1
    #- sam publish --template packaged.yml --region eu-west-1
    #- sam publish --template packaged.yml --region us-east-1
    #- sam publish --template packaged.yml --region us-east-2
    #- sam publish --template packaged.yml --region us-west-1
    #- sam publish --template packaged.yml --region us-west-2

#artifacts:
#  files:
#    - deployspec.yml
#    - packaged.yaml